authenticate vpn

diff --git a/.github/workflows/android-masterCI.yml b/.github/workflows/android-masterCI.yml
--- a/.github/workflows/android-masterCI.yml
+++ b/.github/workflows/android-masterCI.yml
@@ -19,18 +19,23 @@ jobs:
       - name: Install Dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y openconnect curl
+          sudo apt-get install -y openconnect ca-certificates
+
+      - name: Install CA Certificates
+        run: |
+          sudo apt-get install -y ca-certificates
+          sudo update-ca-certificates
 
       - name: Connect to VPN
         id: connect-vpn
         run: |
           echo "Connecting to VPN..."
           # Perform web login and obtain session cookie
-          response=$(curl -k -c cookie.txt -d "user=${{ secrets.VPN_USERNAME }}&password=${{ secrets.VPN_PASSWORD }}" -X POST https://${{ secrets.VPN_GATEWAY }}/global-protect/login.esp)
+          response=$(curl -k -c cookie.txt -d "user=${{ secrets.VPN_USERNAME }}&passwd=${{ secrets.VPN_PASSWORD }}" -X POST https://213.42.155.161/global-protect/login.esp)
           # Extract session ID from cookie
           sessid=$(grep SESSID cookie.txt | awk '{print $NF}')
           # Use session ID to authenticate with openconnect
-          sudo openconnect --user=${{ secrets.VPN_USERNAME }} --passwd-on-stdin --cookie="SESSID=$sessid" https://${{ secrets.VPN_GATEWAY }} --servercert pin-sha256:T/0yX2tT3UIZmGR5de5WKUbEXSHZQBh6Dne7q0rPEm0= --background <<< ${{ secrets.VPN_PASSWORD }}
+          sudo openconnect --user=${{ secrets.VPN_USERNAME }} --cookie="SESSID=$sessid" https://213.42.155.161 --servercert pin-sha256:T/0yX2tT3UIZmGR5de5WKUbEXSHZQBh6Dne7q0rPEm0= --background || (echo "Failed to connect to VPN" && exit 1)
           echo "VPN Connected"
 
       - name: Wait for VPN Connection
